CREATE TABLE `order_addresses` (
  `id` varchar(36) NOT NULL,
  `order_id` varchar(36) NOT NULL,
  `name` varchar(255) NOT NULL,
  `address_line_1` varchar(255) NOT NULL,
  `address_line_2` varchar(255) DEFAULT NULL,
  `city` varchar(255) NOT NULL,
  `county` varchar(255) NOT NULL,
  `postcode` varchar(255) NOT NULL,
  `country` varchar(255) NOT NULL,
  `type` varchar(10) NOT NULL DEFAULT 'billing',
  `created_at` datetime NOT NULL,
  `created_by` varchar(36) NOT NULL,
  `updated_at` datetime NOT NULL,
  `updated_by` varchar(36) NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `deleted_by` varchar(36) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `order_addresses_UN` (`order_id`,`type`),
  KEY `order_addresses_order_id_IDX` (`order_id`) USING BTREE,
  KEY `order_addresses_name_IDX` (`name`) USING BTREE,
  KEY `order_addresses_address_line_1_IDX` (`address_line_1`) USING BTREE,
  KEY `order_addresses_address_line_2_IDX` (`address_line_2`) USING BTREE,
  KEY `order_addresses_city_IDX` (`city`) USING BTREE,
  KEY `order_addresses_county_IDX` (`county`) USING BTREE,
  KEY `order_addresses_postcode_IDX` (`postcode`) USING BTREE,
  KEY `order_addresses_country_IDX` (`country`) USING BTREE,
  KEY `order_addresses_type_IDX` (`type`) USING BTREE,
  KEY `order_addresses_created_at_IDX` (`created_at`) USING BTREE,
  KEY `order_addresses_created_by_IDX` (`created_by`) USING BTREE,
  KEY `order_addresses_updated_at_IDX` (`updated_at`) USING BTREE,
  KEY `order_addresses_updated_by_IDX` (`updated_by`) USING BTREE,
  KEY `order_addresses_deleted_at_IDX` (`deleted_at`) USING BTREE,
  KEY `order_addresses_deleted_by_IDX` (`deleted_by`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;